// *** REGISTER ACTION *** //

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// *** LOGIN ACTION ***//

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// *** RECIPES ***//

export const FETCH_RECIPES_START = "FETCH_RECIPES_START";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAILURE = "FETCH_RECIPES_FAILURE";

export const ADD_RECIPE_START = "ADD_RECIPE_START";
export const ADD_RECIPES_SUCESS = "ADD_RECIPE_SUCCESS";
export const ADD_RECIPES_FAILURE = "ADD_RECIPE_FAILURE";
